const ALERT = "ALERT";

const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";

const NEW_MESSAGE = "NEW_MESSAGE";

const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const  NEW_REQUEST = "NEW_REQUEST";

const   START_TYPING_CHAT = "START_TYPING_CHAT";
const   STOP_TYPING_CHAT = "STOP_TYPING_CHAT";
const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";
const ONLINE_USERS = "ONLINE_USERS";

export  { ALERT, REFETCH_CHATS , NEW_ATTACHMENT, NEW_MESSAGE, NEW_MESSAGE_ALERT, NEW_REQUEST, START_TYPING_CHAT, STOP_TYPING_CHAT,CHAT_JOINED,CHAT_LEAVED,ONLINE_USERS};
